### ISSUE TITLE
Windows opam ignores -j flag

### ISSUE THREAD

**Issue by JasonGross** [avsm/setup-ocaml#74]
Perhaps I'm passing the flags wrong, but I thought that passing `-j 1` was supposed to disable multi-threaded builds.  Yet passing `-j 1` (at least on Windows) does nothing, perhaps because this action seems to set `OPAMJOBS` to 4?  And yet `make` is called with 3 threads? https://github.com/mit-plv/fiat-crypto/pull/966/checks?check_run_id=2547643681#step:16:33  How do I tell this action to disable parallel jobs, but only on Windows?

**Comment by dra27** [comment]
Does dra27/setup-ocaml@windows-jobs work for this, please?

**Comment by JasonGross** [comment]
Indeed, that does seem to work, thanks!

**Comment by dra27** [comment]
Excellent, thanks for confirming! The issue is that the action was running `opam config set jobs 3` - this creates a variable _in the switch_ called `jobs`, rather than altering the global default value for `-j`. So `opam install -j 1` was setting the global `jobs` to `1` but the switch variable took priority.

**Comment by smorimoto** [comment]
I will create a new v1 release later.
